### ISSUE TITLE
POM is borked 

### ISSUE THREAD

**Issue by SticksDev** [Mikedeejay2/Mikedeejay2Lib#51]
The POM for com.mikedeejay2:mikedeejay2lib:jar:1.16.5-20210402.161502-27 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

EDIT: Yeeted the .m2 for it as well, no dice.

**Comment by Mikedeejay2** [comment]
This occurs because the Spigot jar files for NMS are located in the Mikedeejay2Lib project directory. Since the pom.xml uses the build directory as a reference to these files, any sub-plugins that use Mikedeejay2Lib will receive this warning since the plugin build directory is not the same directory as the lib build directory. I'm not sure I can fix this but if I find a way I'll point to it here. Closed for now.

Also, this issue was just a confusion issue, as PluginBase had been changed to BukkitPlugin.
